import React, { useState } from 'react';
import { ContentRow } from '@/lib/types';
import ReactMarkdown from 'react-markdown';
import { Copy, Check, Eye, Code, FileText, Image as ImageIcon, Video, Layers } from 'lucide-react';

interface ContentTabsProps {
  todayRow: ContentRow | null;
}

type TabKey = 'linkedin' | 'medium' | 'instagram' | 'youtube' | 'devto';

export default function ContentTabs({ todayRow }: ContentTabsProps) {
  const [activeTab, setActiveTab] = useState<TabKey>('linkedin');
  const [copiedStates, setCopiedStates] = useState<Record<TabKey, boolean>>({
    linkedin: false,
    medium: false,
    instagram: false,
    youtube: false,
    devto: false,
  });

  if (!todayRow) {
    return (
      <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-8 text-center">
        <Layers className="w-12 h-12 text-zinc-600 mx-auto mb-4" />
        <h3 className="text-white text-lg font-semibold mb-1">No Content Available</h3>
        <p className="text-zinc-500 text-sm max-w-sm mx-auto">
          Today's content pipeline has not run yet. Run the pipeline to generate social posts, articles, and scripts.
        </p>
      </div>
    );
  }

  const tabs = [
    { key: 'linkedin', label: 'LinkedIn Post', icon: FileText, image: todayRow.linkedinImage, content: todayRow.linkedinPost || '', isMarkdown: false },
    { key: 'medium', label: 'Medium Article', icon: FileText, image: todayRow.mediumImage, content: todayRow.mediumArticle || '', isMarkdown: true },
    { key: 'instagram', label: 'Instagram Script', icon: Video, image: todayRow.igImage, content: todayRow.igScript || '', isMarkdown: false },
    { key: 'youtube', label: 'YouTube Script', icon: Video, image: null, content: todayRow.ytScript || '', isMarkdown: false },
    { key: 'devto', label: 'Dev.to Article', icon: Code, image: null, content: todayRow.devtoArticle || '', isMarkdown: true },
  ] as const;

  const currentTab = tabs.find(t => t.key === activeTab) || tabs[0];

  const handleCopy = async (key: TabKey, text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedStates(prev => ({ ...prev, [key]: true }));
      setTimeout(() => {
        setCopiedStates(prev => ({ ...prev, [key]: false }));
      }, 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
      {/* TABS HEADER */}
      <div className="flex border-b border-zinc-800 bg-zinc-950 overflow-x-auto scrollbar-none">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = tab.key === activeTab;
          return (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`flex items-center space-x-2 px-6 py-4 border-b-2 text-sm font-medium whitespace-nowrap transition-all duration-200 ${
                isActive
                  ? 'border-purple-500 text-purple-400 bg-zinc-900/50'
                  : 'border-transparent text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/20'
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
              {!tab.content && todayRow.status !== 'Error' && (
                <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse ml-2" />
              )}
            </button>
          );
        })}
      </div>

      {/* TAB CONTENT PANEL */}
      <div className="p-6">
        {/* If the current tab content is not generated yet */}
        {!currentTab.content ? (
          <div className="py-12 text-center text-zinc-500">
            <RefreshIcon className="w-8 h-8 mx-auto mb-2 animate-spin text-zinc-600" />
            <p className="text-sm">Content is being generated by Agent 2...</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* TEXT PANEL */}
            <div className={`${currentTab.image ? 'lg:col-span-8' : 'lg:col-span-12'} flex flex-col`}>
              <div className="flex items-center justify-between mb-4 pb-3 border-b border-zinc-850">
                <span className="text-zinc-400 text-xs font-semibold uppercase tracking-wider flex items-center space-x-1.5">
                  <Eye className="w-3.5 h-3.5" />
                  <span>Preview ({currentTab.isMarkdown ? 'Markdown Rendered' : 'Plain Text'})</span>
                </span>
                <button
                  onClick={() => handleCopy(currentTab.key, currentTab.content)}
                  className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all duration-200 ${
                    copiedStates[currentTab.key]
                      ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                      : 'bg-zinc-800 text-zinc-300 border-zinc-700 hover:bg-zinc-700 hover:text-white'
                  }`}
                >
                  {copiedStates[currentTab.key] ? (
                    <>
                      <Check className="w-3.5 h-3.5" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy to Clipboard</span>
                    </>
                  )}
                </button>
              </div>

              {/* RENDER CONTAINER */}
              <div className="bg-zinc-950/40 border border-zinc-800/60 rounded-xl p-6 overflow-y-auto max-h-[600px] text-zinc-350 select-text">
                {currentTab.isMarkdown ? (
                  <ReactMarkdown
                    components={{
                      h1: ({ ...props }) => <h1 className="text-2xl font-bold text-white mt-6 mb-3 border-b border-zinc-800 pb-1.5" {...props} />,
                      h2: ({ ...props }) => <h2 className="text-xl font-semibold text-white mt-5 mb-2.5" {...props} />,
                      h3: ({ ...props }) => <h3 className="text-lg font-medium text-white mt-4 mb-2" {...props} />,
                      p: ({ ...props }) => <p className="text-zinc-300 mb-4 leading-relaxed font-sans" {...props} />,
                      code: ({ ...props }) => <code className="bg-zinc-950 text-purple-300 px-1.5 py-0.5 rounded font-mono text-sm border border-zinc-800/40" {...props} />,
                      pre: ({ ...props }) => <pre className="bg-zinc-950 text-zinc-200 p-4 rounded-lg overflow-x-auto font-mono text-xs border border-zinc-800 mb-4 whitespace-pre-wrap" {...props} />,
                      ul: ({ ...props }) => <ul className="list-disc pl-5 mb-4 text-zinc-300 space-y-1" {...props} />,
                      ol: ({ ...props }) => <ol className="list-decimal pl-5 mb-4 text-zinc-300 space-y-1" {...props} />,
                      li: ({ ...props }) => <li className="text-zinc-300" {...props} />,
                      blockquote: ({ ...props }) => <blockquote className="border-l-4 border-purple-500 pl-4 italic text-zinc-400 mb-4" {...props} />,
                    }}
                  >
                    {currentTab.content}
                  </ReactMarkdown>
                ) : (
                  <div className="whitespace-pre-wrap font-sans text-zinc-300 leading-relaxed text-sm">
                    {currentTab.content}
                  </div>
                )}
              </div>
            </div>

            {/* IMAGE PREVIEW PANEL */}
            {currentTab.image && (
              <div className="lg:col-span-4 flex flex-col">
                <span className="text-zinc-400 text-xs font-semibold uppercase tracking-wider flex items-center space-x-1.5 mb-4">
                  <ImageIcon className="w-3.5 h-3.5" />
                  <span>Generated Artwork</span>
                </span>
                
                <div className="bg-zinc-950/30 border border-zinc-850 rounded-xl overflow-hidden p-3 flex flex-col justify-between h-[400px]">
                  <div className="bg-zinc-950 rounded-lg overflow-hidden flex-grow flex items-center justify-center relative border border-zinc-900 group">
                    {/* Render image from relative path served by Next.js */}
                    <img 
                      src={currentTab.image} 
                      alt={`${currentTab.label} Visual`} 
                      className="max-h-full max-w-full object-contain transition-all duration-300 group-hover:scale-[1.02]"
                    />
                  </div>
                  <div className="mt-3 flex items-center justify-between text-xs text-zinc-500">
                    <span>Source: {currentTab.image}</span>
                    <a
                      href={currentTab.image}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-purple-400 hover:text-purple-300 transition-colors"
                    >
                      Open full resolution
                    </a>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function RefreshIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.72 2.78L21 8" />
      <polyline points="21 3 21 8 16 8" />
    </svg>
  );
}
